// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC0JfveJxGLqcDVKcd1d6V4LE_3clTRm8',
    appId: '1:854364383089:android:00bd3b047366cdd68978d0',
    messagingSenderId: '854364383089',
    projectId: 'telegramm-31fa2',
    storageBucket: 'telegramm-31fa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-19CXlboAVHFAiTdkdXjIT6fDQJeNlBE',
    appId: '1:854364383089:ios:2266ca2811ac26d18978d0',
    messagingSenderId: '854364383089',
    projectId: 'telegramm-31fa2',
    storageBucket: 'telegramm-31fa2.appspot.com',
    iosBundleId: 'com.example.telegramm',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYh_GVIccbKBLUnUeaNJntNvWotOV6Hjg',
    appId: '1:854364383089:web:17b9a065c3dcf4788978d0',
    messagingSenderId: '854364383089',
    projectId: 'telegramm-31fa2',
    authDomain: 'telegramm-31fa2.firebaseapp.com',
    storageBucket: 'telegramm-31fa2.appspot.com',
    measurementId: 'G-XNT8VHEZQK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-19CXlboAVHFAiTdkdXjIT6fDQJeNlBE',
    appId: '1:854364383089:ios:2266ca2811ac26d18978d0',
    messagingSenderId: '854364383089',
    projectId: 'telegramm-31fa2',
    storageBucket: 'telegramm-31fa2.appspot.com',
    iosBundleId: 'com.example.telegramm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYh_GVIccbKBLUnUeaNJntNvWotOV6Hjg',
    appId: '1:854364383089:web:137104c901d30d248978d0',
    messagingSenderId: '854364383089',
    projectId: 'telegramm-31fa2',
    authDomain: 'telegramm-31fa2.firebaseapp.com',
    storageBucket: 'telegramm-31fa2.appspot.com',
    measurementId: 'G-2THVERQBB4',
  );

}